# Generated by Django 4.2.7 on 2023-11-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='blodd',
            new_name='blood',
        ),
    ]
