# Generated by Django 4.2.7 on 2023-11-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_rename_blodd_patient_blood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('detail', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
